{% set name = "stellarphot" %}
{% set version = "2.1.2" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/stellarphot-{{ version }}.tar.gz
  sha256: a631209550ec5ac5b1ee1d02a3c2e397695c51e9d84977e809f4c6fe440f647b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - astropy-base >=5
    - astroquery
    - astrowidgets <0.4.0
    - bottleneck
    - ccdproc
    - ginga
    - ipyautoui >=0.7.19
    - ipyfilechooser
    - ipywidgets
    - jupyter_app_launcher >=0.3.0
    - lightkurve >=2.6.0
    - matplotlib-base
    - papermill
    - pandas
    - photutils >=2,<3
    - platformdirs
    - pydantic >=2
    - python >={{ python_min }}
    - pytransit
    - lmfit
    - pyyaml
    - regions
    - jupyterlab

test:
  imports:
    - stellarphot
  commands:
    - pip check
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/feder-observatory/stellarphot
  summary: A package for performing stellar photometry.
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - mwcraig
