{% set name = "stellarphot" %}
{% set version = "1.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stellarphot-{{ version }}.tar.gz
  sha256: fffb47bfbc52f64986d7d6be2603ad338ba20f859f14cb8b36784a52b621b813

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - astropy >=5,<5.1
    - astroquery
    - astrowidgets
    - bottleneck
    - ccdproc
    - gatspy
    - ginga
    - ipywidgets
    - matplotlib-base
    - pandas
    - photutils >=1
    - python >=3.7
    - pyyaml
    - batman-package
    - jsonschema <4,>=3.0.2

test:
  imports:
    - stellarphot
    - stellarphot.analysis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/stellarphot/stellarphot
  summary: A package for performing stellar photometry.
  license: BSD-3-Clause
  license_file: licenses/LICENSE.rst

extra:
  recipe-maintainers:
    - mwcraig
