{% set name = "stellarphot" %}
{% set version = "2.0.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/stellarphot-{{ version }}.tar.gz
  sha256: 934c731f6a040fb29b837fc239361b8f68785bd4cf2f2745aaea9c584040310d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - astropy-base
    - astroquery
    - astrowidgets
    - bottleneck
    - ccdproc
    - ginga
    - ipyautoui >=0.7.19
    - ipyfilechooser
    - ipywidgets
    - jupyter_app_launcher >=0.3.0
    - lightkurve
    - matplotlib-base
    - papermill
    - pandas
    - photutils >=2
    - pydantic >=2
    - python >={{ python_min }}
    - pyyaml
    - batman-package
    - jsonschema <4,>=3.0.2
    - ipyfilechooser
    - aggdraw
    - jupyterlab

test:
  imports:
    - stellarphot
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/stellarphot/stellarphot
  summary: A package for performing stellar photometry.
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - mwcraig
