{% set name = "stellarphot" %}
{% set version = "1.4.14" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stellarphot-{{ version }}.tar.gz
  sha256: 1bba0d7d4b2ba0f7249b997d2207bbf8dfcc1f60d9d44df8e189c91904d3b2c4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - astropy >=5
    - astroquery
    - astrowidgets
    - bottleneck
    - ccdproc
    - ginga
    - ipywidgets
    - matplotlib-base
    - pandas
    - photutils >=1
    - python >=3.7
    - pyyaml
    - batman-package
    - jsonschema <4,>=3.0.2
    - ipyfilechooser
    - aggdraw
    - jupyterlab

test:
  imports:
    - stellarphot
    - stellarphot.analysis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/stellarphot/stellarphot
  summary: A package for performing stellar photometry.
  license: BSD-3-Clause
  license_file: licenses/LICENSE.rst

extra:
  recipe-maintainers:
    - mwcraig
